#CSE499A

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# For Filtering the warnings
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/content/bgd2018.csv')

In [ ]:
df.head()

,pid,psu,stratum,division,urbanrural,wstep1,wstep2,wstep3,agerange,sex,...,b5,b6,b8,b9,b10,b14,b15,b16,b17,ldl
0,E11-1-1,1,102,1,Urban,2289.934326,2289.934326,2225.452881,18-29,0,...,97.0,NaN,179.0,NaN,2.0,37.599998,30.0,105.0,37.0,121.000000
1,E11-10-1,1,102,1,Urban,1202.908813,1202.908813,NaN,45-59,0,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E11-100-1,48,101,1,Rural,7604.362305,7604.362305,12915.715820,30-44,0,...,100.0,NaN,168.0,NaN,2.0,21.000000,15.0,140.0,29.0,111.000000
3,E11-101-1,49,101,1,Rural,7710.941895,7710.941895,7493.812012,18-29,0,...,90.0,NaN,134.0,NaN,2.0,29.000000,20.0,68.0,43.0,77.400002
4,E11-102-1,49,101,1,Rural,4049.076172,4049.076172,6877.199219,30-44,0,...,99.0,NaN,231.0,NaN,2.0,235.000000,120.0,235.0,33.0,151.000000

In [ ]:
columns_to_keep = ['psu', 'stratum', 'division', 'urbanrural', 'wstep2', 'sex', 'age', 'c4', 'c7', 't1', 't3', 't5a', 't5b', 't5c', 't5d', 't5e', 't5f', 't5g', 't8', 't14a', 't14c', 't14e', 'a1', 'a3', 'd5a', 'd8a', 'dx4_2', 'dx4_3', 'dx4_4', 'dx4_5', 'dx4_6', 'dx6', 'h1', 'h2a', 'hx1', 'h6', 'h7a', 'hx5', 'h9', 'h12', 'h13a', 'hx9', 'h17', 'h18', 'h19', 'h20a', 'h20b', 'h20d', 'h20f', 'cx1', 'cx2', 'm4a', 'm4b', 'm5a', 'm5b', 'm6a', 'm6b', 'm8', 'm11', 'm12', 'm14', 'm15', 'm16c', 'b5', 'b6', 'b8', 'b14', 'b15', 'b16', 'b17','ldl']

df = df[columns_to_keep]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8185 entries, 0 to 8184
Data columns (total 71 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   psu         8185 non-null   int64
 1   stratum     8185 non-null   int64
 2   division    8185 non-null   int64
 3   urbanrural  8185 non-null   object
 4   wstep2      8185 non-null   float64
 5   sex         8185 non-null   int64
 6   age         8185 non-null   int64
 7   c4          8185 non-null   int64
 8   c7          8185 non-null   int64
 9   t1          8185 non-null   int64
 10  t3          1923 non-null   float64
 11  t5a         1834 non-null   float64
 12  t5b         1834 non-null   float64
 13  t5c         1834 non-null   float64
 14  t5d         1834 non-null   float64
 15  t5e         1834 non-null   float64
 16  t5f         1834 non-null   float64
 17  t5g         1834 non-null   float64
 18  t8          6262 non-null   float64
 19  t14a        2349 non-null   float64
 20  t14c        2349 non-null   float64
 21  t14e        2349 non-null   float64
 22  a1          8185 non-null   int64
 23  a3          320 non-null    float64
 24  d5a         8185 non-null   int64
 25  d8a         8185 non-null   int64
 26  dx4_2       8185 non-null   bool
 27  dx4_3       8185 non-null   bool
 28  dx4_4       8185 non-null   bool
 29  dx4_5       8185 non-null   bool
 30  dx4_6       8185 non-null   bool
 31  dx6         8185 non-null   int64
 32  h1          8185 non-null   int64
 33  h2a         6060 non-null   float64
 34  hx1         1409 non-null   float64
 35  h6          8185 non-null   int64
 36  h7a         2386 non-null   float64
 37  hx5         438 non-null    float64
 38  h9          538 non-null    float64
 39  h12         8185 non-null   int64
 40  h13a        514 non-null    float64
 41  hx9         250 non-null    float64
 42  h17         8185 non-null   int64
 43  h18         8185 non-null   int64
 44  h19         8185 non-null   int64
 45  h20a        3977 non-null   float64
 46  h20b        3977 non-null   float64
 47  h20d        3977 non-null   float64
 48  h20f        3977 non-null   float64
 49  cx1         4364 non-null   float64
 50  cx2         270 non-null    float64
 51  m4a         8157 non-null   float64
 52  m4b         8157 non-null   float64
 53  m5a         8154 non-null   float64
 54  m5b         8154 non-null   float64
 55  m6a         8154 non-null   float64
 56  m6b         8154 non-null   float64
 57  m8          4354 non-null   float64
 58  m11         8018 non-null   float64
 59  m12         8018 non-null   float64
 60  m14         8018 non-null   float64
 61  m15         8018 non-null   float64
 62  m16c        8154 non-null   float64
 63  b5          7057 non-null   float64
 64  b6          369 non-null    float64
 65  b8          7199 non-null   float64
 66  b14         7026 non-null   float64
 67  b15         7022 non-null   float64
 68  b16         7199 non-null   float64
 69  b17         7199 non-null   float64
 70  ldl         7192 non-null   float64
dtypes: bool(5), float64(47), int64(18), object(1)
memory usage: 4.2+ MB

In [ ]:
df.head()

,psu,stratum,division,urbanrural,wstep2,sex,age,c4,c7,t1,...,m15,m16c,b5,b6,b8,b14,b15,b16,b17,ldl
0,1,102,1,Urban,2289.934326,0,22,0,2,2,...,88.0,72.0,97.0,NaN,179.0,37.599998,30.0,105.0,37.0,121.000000
1,1,102,1,Urban,1202.908813,0,50,12,2,2,...,96.0,87.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
2,48,101,1,Rural,7604.362305,0,39,0,2,2,...,92.0,91.0,100.0,NaN,168.0,21.000000,15.0,140.0,29.0,111.000000
3,49,101,1,Rural,7710.941895,0,29,0,2,2,...,98.0,92.0,90.0,NaN,134.0,29.000000,20.0,68.0,43.0,77.400002
4,49,101,1,Rural,4049.076172,0,32,9,2,2,...,93.0,82.0,99.0,NaN,231.0,235.000000,120.0,235.0,33.0,151.000000

In [ ]:
df.shape

(8185, 71)

In [ ]:
df.keys()

Index(['psu', 'stratum', 'division', 'urbanrural', 'wstep2', 'sex', 'age',
       'c4', 'c7', 't1', 't3', 't5a', 't5b', 't5c', 't5d', 't5e', 't5f', 't5g',
       't8', 't14a', 't14c', 't14e', 'a1', 'a3', 'd5a', 'd8a', 'dx4_2',
       'dx4_3', 'dx4_4', 'dx4_5', 'dx4_6', 'dx6', 'h1', 'h2a', 'hx1', 'h6',
       'h7a', 'hx5', 'h9', 'h12', 'h13a', 'hx9', 'h17', 'h18', 'h19', 'h20a',
       'h20b', 'h20d', 'h20f', 'cx1', 'cx2', 'm4a', 'm4b', 'm5a', 'm5b', 'm6a',
       'm6b', 'm8', 'm11', 'm12', 'm14', 'm15', 'm16c', 'b5', 'b6', 'b8',
       'b14', 'b15', 'b16', 'b17', 'ldl'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8185 entries, 0 to 8184
Data columns (total 71 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   psu         8185 non-null   int64
 1   stratum     8185 non-null   int64
 2   division    8185 non-null   int64
 3   urbanrural  8185 non-null   object
 4   wstep2      8185 non-null   float64
 5   sex         8185 non-null   int64
 6   age         8185 non-null   int64
 7   c4          8185 non-null   int64
 8   c7          8185 non-null   int64
 9   t1          8185 non-null   int64
 10  t3          1923 non-null   float64
 11  t5a         1834 non-null   float64
 12  t5b         1834 non-null   float64
 13  t5c         1834 non-null   float64
 14  t5d         1834 non-null   float64
 15  t5e         1834 non-null   float64
 16  t5f         1834 non-null   float64
 17  t5g         1834 non-null   float64
 18  t8          6262 non-null   float64
 19  t14a        2349 non-null   float64
 20  t14c        2349 non-null   float64
 21  t14e        2349 non-null   float64
 22  a1          8185 non-null   int64
 23  a3          320 non-null    float64
 24  d5a         8185 non-null   int64
 25  d8a         8185 non-null   int64
 26  dx4_2       8185 non-null   bool
 27  dx4_3       8185 non-null   bool
 28  dx4_4       8185 non-null   bool
 29  dx4_5       8185 non-null   bool
 30  dx4_6       8185 non-null   bool
 31  dx6         8185 non-null   int64
 32  h1          8185 non-null   int64
 33  h2a         6060 non-null   float64
 34  hx1         1409 non-null   float64
 35  h6          8185 non-null   int64
 36  h7a         2386 non-null   float64
 37  hx5         438 non-null    float64
 38  h9          538 non-null    float64
 39  h12         8185 non-null   int64
 40  h13a        514 non-null    float64
 41  hx9         250 non-null    float64
 42  h17         8185 non-null   int64
 43  h18         8185 non-null   int64
 44  h19         8185 non-null   int64
 45  h20a        3977 non-null   float64
 46  h20b        3977 non-null   float64
 47  h20d        3977 non-null   float64
 48  h20f        3977 non-null   float64
 49  cx1         4364 non-null   float64
 50  cx2         270 non-null    float64
 51  m4a         8157 non-null   float64
 52  m4b         8157 non-null   float64
 53  m5a         8154 non-null   float64
 54  m5b         8154 non-null   float64
 55  m6a         8154 non-null   float64
 56  m6b         8154 non-null   float64
 57  m8          4354 non-null   float64
 58  m11         8018 non-null   float64
 59  m12         8018 non-null   float64
 60  m14         8018 non-null   float64
 61  m15         8018 non-null   float64
 62  m16c        8154 non-null   float64
 63  b5          7057 non-null   float64
 64  b6          369 non-null    float64
 65  b8          7199 non-null   float64
 66  b14         7026 non-null   float64
 67  b15         7022 non-null   float64
 68  b16         7199 non-null   float64
 69  b17         7199 non-null   float64
 70  ldl         7192 non-null   float64
dtypes: bool(5), float64(47), int64(18), object(1)
memory usage: 4.2+ MB

In [ ]:
df.describe()

,psu,stratum,division,wstep2,sex,age,c4,c7,t1,t3,...,m15,m16c,b5,b6,b8,b14,b15,b16,b17,ldl
count,8185.000000,8185.000000,8185.000000,8185.000000,8185.000000,8185.000000,8185.000000,8185.000000,8185.000000,1923.000000,...,8018.000000,8154.000000,7057.000000,369.000000,7199.000000,7026.000000,7022.000000,7199.000000,7199.000000,7192.000000
mean,249.385950,389.943433,4.509591,13949.547057,0.464753,39.074893,9.870250,2.068418,1.765058,18.251690,...,92.052776,78.042556,99.582684,1.100271,169.257258,111.594619,89.246369,146.602445,38.164745,101.790462
std,142.359251,162.525021,2.279673,17108.271825,0.498787,12.299860,17.466615,0.667615,0.423988,7.104914,...,21.857463,12.205075,35.939007,0.300769,45.717705,72.530581,72.879044,101.136485,11.305691,36.249586
min,1.000000,101.000000,1.000000,568.078613,0.000000,18.000000,0.000000,1.000000,1.000000,8.000000,...,45.000000,31.000000,0.000000,1.000000,0.000000,4.000000,0.000000,0.000000,0.000000,-192.000000
25%,125.000000,301.000000,3.000000,3300.986572,0.000000,30.000000,1.000000,2.000000,2.000000,15.000000,...,85.000000,70.000000,84.000000,1.000000,144.000000,55.000000,35.000000,85.000000,32.000000,80.800003
50%,250.000000,451.000000,5.000000,9503.190430,0.000000,38.000000,5.000000,2.000000,2.000000,17.000000,...,91.000000,77.000000,92.000000,1.000000,168.000000,94.000000,65.000000,123.000000,37.000000,100.800003
75%,371.000000,502.000000,6.000000,17502.605470,1.000000,48.000000,10.000000,2.000000,2.000000,20.000000,...,97.000000,86.000000,102.000000,1.000000,195.000000,156.524998,120.000000,180.000000,43.000000,122.650000
max,496.000000,602.000000,8.000000,260925.000000,1.000000,69.000000,88.000000,5.000000,2.000000,77.000000,...,888.000000,136.000000,535.000000,2.000000,650.000000,974.000000,625.000000,1364.000000,340.000000,367.799988

Null Value Remove

In [ ]:
df['t3'].fillna(df['t3'].mean(), inplace=True)
df['t3'].fillna(df['t3'].median(), inplace=True)
df['t3'].fillna(df['t3'].mode()[0], inplace=True)

In [ ]:
df['t5a'].fillna(df['t5a'].mean(), inplace=True)
df['t5a'].fillna(df['t5a'].median(), inplace=True)
df['t5a'].fillna(df['t5a'].mode()[0], inplace=True)

In [ ]:
df['t5b'].fillna(df['t5b'].mean(), inplace=True)
df['t5b'].fillna(df['t5b'].median(), inplace=True)
df['t5b'].fillna(df['t5b'].mode()[0], inplace=True)

In [ ]:
df['t5c'].fillna(df['t5c'].mean(), inplace=True)
df['t5c'].fillna(df['t5c'].median(), inplace=True)
df['t5c'].fillna(df['t5c'].mode()[0], inplace=True)

In [ ]:
df['t5d'].fillna(df['t5d'].mean(), inplace=True)
df['t5d'].fillna(df['t5d'].median(), inplace=True)
df['t5d'].fillna(df['t5d'].mode()[0], inplace=True)

In [ ]:
df['t5e'].fillna(df['t5e'].mean(), inplace=True)
df['t5e'].fillna(df['t5e'].median(), inplace=True)
df['t5e'].fillna(df['t5e'].mode()[0], inplace=True)

In [ ]:
df['t5f'].fillna(df['t5f'].mean(), inplace=True)
df['t5f'].fillna(df['t5f'].median(), inplace=True)
df['t5f'].fillna(df['t5f'].mode()[0], inplace=True)

In [ ]:
df['t5g'].fillna(df['t5g'].mean(), inplace=True)
df['t5g'].fillna(df['t5g'].median(), inplace=True)
df['t5g'].fillna(df['t5g'].mode()[0], inplace=True)

In [ ]:
df['t8'].fillna(df['t8'].mean(), inplace=True)
df['t8'].fillna(df['t8'].median(), inplace=True)
df['t8'].fillna(df['t8'].mode()[0], inplace=True)

In [ ]:
df['t14a'].fillna(df['t14a'].mean(), inplace=True)
df['t14a'].fillna(df['t14a'].median(), inplace=True)
df['t14a'].fillna(df['t14a'].mode()[0], inplace=True)

In [ ]:
df['t14c'].fillna(df['t14c'].mean(), inplace=True)
df['t14c'].fillna(df['t14c'].median(), inplace=True)
df['t14c'].fillna(df['t14c'].mode()[0], inplace=True)

In [ ]:
df['t14e'].fillna(df['t14e'].mean(), inplace=True)
df['t14e'].fillna(df['t14e'].median(), inplace=True)
df['t14e'].fillna(df['t14e'].mode()[0], inplace=True)

In [ ]:
df['a3'].fillna(df['a3'].mean(), inplace=True)
df['a3'].fillna(df['a3'].median(), inplace=True)
df['a3'].fillna(df['a3'].mode()[0], inplace=True)

In [ ]:
df['h2a'].fillna(df['h2a'].mean(), inplace=True)
df['h2a'].fillna(df['h2a'].median(), inplace=True)
df['h2a'].fillna(df['h2a'].mode()[0], inplace=True)

In [ ]:
df['hx1'].fillna(df['hx1'].mean(), inplace=True)
df['hx1'].fillna(df['hx1'].median(), inplace=True)
df['hx1'].fillna(df['hx1'].mode()[0], inplace=True)

In [ ]:
df['h7a'].fillna(df['h7a'].mean(), inplace=True)
df['h7a'].fillna(df['h7a'].median(), inplace=True)
df['h7a'].fillna(df['h7a'].mode()[0], inplace=True)

In [ ]:
df['hx5'].fillna(df['hx5'].mean(), inplace=True)
df['hx5'].fillna(df['hx5'].median(), inplace=True)
df['hx5'].fillna(df['hx5'].mode()[0], inplace=True)

In [ ]:
df['h9'].fillna(df['h9'].mean(), inplace=True)
df['h9'].fillna(df['h9'].median(), inplace=True)
df['h9'].fillna(df['h9'].mode()[0], inplace=True)

In [ ]:
df['h13a'].fillna(df['h13a'].mean(), inplace=True)
df['h13a'].fillna(df['h13a'].median(), inplace=True)
df['h13a'].fillna(df['h13a'].mode()[0], inplace=True)

In [ ]:
df['hx9'].fillna(df['hx9'].mean(), inplace=True)
df['hx9'].fillna(df['hx9'].median(), inplace=True)
df['hx9'].fillna(df['hx9'].mode()[0], inplace=True)

In [ ]:
df['h20a'].fillna(df['h20a'].mean(), inplace=True)
df['h20a'].fillna(df['h20a'].median(), inplace=True)
df['h20a'].fillna(df['h20a'].mode()[0], inplace=True)

In [ ]:
df['h20b'].fillna(df['h20b'].mean(), inplace=True)
df['h20b'].fillna(df['h20b'].median(), inplace=True)
df['h20b'].fillna(df['h20b'].mode()[0], inplace=True)

In [ ]:
df['h20d'].fillna(df['h20d'].mean(), inplace=True)
df['h20d'].fillna(df['h20d'].median(), inplace=True)
df['h20d'].fillna(df['h20d'].mode()[0], inplace=True)

In [ ]:
df['h20f'].fillna(df['h20f'].mean(), inplace=True)
df['h20f'].fillna(df['h20f'].median(), inplace=True)
df['h20f'].fillna(df['h20f'].mode()[0], inplace=True)

In [ ]:
df['cx1'].fillna(df['cx1'].mean(), inplace=True)
df['cx1'].fillna(df['cx1'].median(), inplace=True)
df['cx1'].fillna(df['cx1'].mode()[0], inplace=True)

In [ ]:
df['cx2'].fillna(df['cx2'].mean(), inplace=True)
df['cx2'].fillna(df['cx2'].median(), inplace=True)
df['cx2'].fillna(df['cx2'].mode()[0], inplace=True)

In [ ]:
df['m4a'].fillna(df['m4a'].mean(), inplace=True)
df['m4a'].fillna(df['m4a'].median(), inplace=True)
df['m4a'].fillna(df['m4a'].mode()[0], inplace=True)

In [ ]:
df['m4b'].fillna(df['m4b'].mean(), inplace=True)
df['m4b'].fillna(df['m4b'].median(), inplace=True)
df['m4b'].fillna(df['m4b'].mode()[0], inplace=True)

In [ ]:
df['m5a'].fillna(df['m5a'].mean(), inplace=True)
df['m5a'].fillna(df['m5a'].median(), inplace=True)
df['m5a'].fillna(df['m5a'].mode()[0], inplace=True)

In [ ]:
df['m5b'].fillna(df['m5b'].mean(), inplace=True)
df['m5b'].fillna(df['m5b'].median(), inplace=True)
df['m5b'].fillna(df['m5b'].mode()[0], inplace=True)

In [ ]:
df['m6a'].fillna(df['m6a'].mean(), inplace=True)
df['m6a'].fillna(df['m6a'].median(), inplace=True)
df['m6a'].fillna(df['m6a'].mode()[0], inplace=True)

In [ ]:
df['m6b'].fillna(df['m6b'].mean(), inplace=True)
df['m6b'].fillna(df['m6b'].median(), inplace=True)
df['m6b'].fillna(df['m6b'].mode()[0], inplace=True)

In [ ]:
df['m8'].fillna(df['m8'].mean(), inplace=True)
df['m8'].fillna(df['m8'].median(), inplace=True)
df['m8'].fillna(df['m8'].mode()[0], inplace=True)

In [ ]:
df['m11'].fillna(df['m11'].mean(), inplace=True)
df['m11'].fillna(df['m11'].median(), inplace=True)
df['m11'].fillna(df['m11'].mode()[0], inplace=True)

In [ ]:
df['m12'].fillna(df['m12'].mean(), inplace=True)
df['m12'].fillna(df['m12'].median(), inplace=True)
df['m12'].fillna(df['m12'].mode()[0], inplace=True)

In [ ]:
df['m14'].fillna(df['m14'].mean(), inplace=True)
df['m14'].fillna(df['m14'].median(), inplace=True)
df['m14'].fillna(df['m14'].mode()[0], inplace=True)

In [ ]:
df['m15'].fillna(df['m15'].mean(), inplace=True)
df['m15'].fillna(df['m15'].median(), inplace=True)
df['m15'].fillna(df['m15'].mode()[0], inplace=True)

In [ ]:
df['m16c'].fillna(df['m16c'].mean(), inplace=True)
df['m16c'].fillna(df['m16c'].median(), inplace=True)
df['m16c'].fillna(df['m16c'].mode()[0], inplace=True)

In [ ]:
df['b5'].fillna(df['b5'].mean(), inplace=True)
df['b5'].fillna(df['b5'].median(), inplace=True)
df['b5'].fillna(df['b5'].mode()[0], inplace=True)

In [ ]:
df['b6'].fillna(df['b6'].mean(), inplace=True)
df['b6'].fillna(df['b6'].median(), inplace=True)
df['b6'].fillna(df['b6'].mode()[0], inplace=True)

In [ ]:
df['b8'].fillna(df['b8'].mean(), inplace=True)
df['b8'].fillna(df['b8'].median(), inplace=True)
df['b8'].fillna(df['b8'].mode()[0], inplace=True)

In [ ]:
df['b14'].fillna(df['b14'].mean(), inplace=True)
df['b14'].fillna(df['b14'].median(), inplace=True)
df['b14'].fillna(df['b14'].mode()[0], inplace=True)

In [ ]:
df['b15'].fillna(df['b15'].mean(), inplace=True)
df['b15'].fillna(df['b15'].median(), inplace=True)
df['b15'].fillna(df['b15'].mode()[0], inplace=True)

In [ ]:
df['b16'].fillna(df['b16'].mean(), inplace=True)
df['b16'].fillna(df['b16'].median(), inplace=True)
df['b16'].fillna(df['b16'].mode()[0], inplace=True)

In [ ]:
df['b17'].fillna(df['b17'].mean(), inplace=True)
df['b17'].fillna(df['b17'].median(), inplace=True)
df['b17'].fillna(df['b17'].mode()[0], inplace=True)

In [ ]:
df['ldl'].fillna(df['ldl'].mean(), inplace=True)
df['ldl'].fillna(df['ldl'].median(), inplace=True)
df['ldl'].fillna(df['ldl'].mode()[0], inplace=True)

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.head()

In [ ]:
df['dx4_2'] = df['dx4_2'].map({True: 1, False: 0})

In [ ]:
df['dx4_3'] = df['dx4_3'].map({True: 1, False: 0})

In [ ]:
df['dx4_4'] = df['dx4_4'].map({True: 1, False: 0})

In [ ]:
df['dx4_5'] = df['dx4_5'].map({True: 1, False: 0})

In [ ]:
df['dx4_6'] = df['dx4_6'].map({True: 1, False: 0})

In [ ]:
df['urbanrural'].replace('Rural', 0, inplace=True)
df['urbanrural'].replace('Urban', 1, inplace=True)

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
# Save the modified DataFrame to a new CSV file
#modified_csv_path = 'modified_file.csv'
#df.to_csv(modified_csv_path, index=False)

In [ ]:
#from google.colab import files

# Download the CSV file
#files.download(modified_csv_path)

In [ ]:
X = df.drop(columns=['hx1']).to_numpy()
y = df['hx1'].to_numpy()

In [ ]:
import numpy as np
from sklearn import metrics
import pandas as pd
from sklearn.cluster import KMeans, AgglomerativeClustering, SpectralClustering, MiniBatchKMeans, DBSCAN
from sklearn.metrics import silhouette_score
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt

# Sample data (X) and true labels (y) should be defined before this code block
# Example: X, y = your_data, your_labels

def tune_dbscan(X):
    # Determine a good value for eps using a k-distance graph
    neighbors = NearestNeighbors(n_neighbors=5)
    neighbors_fit = neighbors.fit(X)
    distances, indices = neighbors_fit.kneighbors(X)
    distances = np.sort(distances[:, 4], axis=0)

    plt.plot(distances)
    plt.xlabel('Points sorted by distance')
    plt.ylabel('5th Nearest Neighbor Distance')
    plt.show()

    # Try different values of eps and min_samples
    eps_values = [0.5, 0.7, 1.0]  # Adjust these values based on the k-distance graph
    min_samples_values = [3, 5, 10]

    best_score = -1
    best_params = {}

    for eps in eps_values:
        for min_samples in min_samples_values:
            dbscan = DBSCAN(eps=eps, min_samples=min_samples)
            labels = dbscan.fit_predict(X)

            # Check the number of clusters
            n_clusters = len(set(labels)) - (1 if -1 in labels else 0)

            if n_clusters > 1:
                score = silhouette_score(X, labels)
                print(f'eps: {eps}, min_samples: {min_samples}, silhouette score: {score}')
                if score > best_score:
                    best_score = score
                    best_params = {'eps': eps, 'min_samples': min_samples}

    return best_params, best_score

# Tune DBSCAN parameters
best_dbscan_params, best_dbscan_score = tune_dbscan(X)

# Define clustering algorithms
number_of_clusters = 2
algorithms = [
    KMeans(n_clusters=number_of_clusters, random_state=1),
    MiniBatchKMeans(n_clusters=number_of_clusters, random_state=1),
    AgglomerativeClustering(n_clusters=number_of_clusters),
    SpectralClustering(n_clusters=number_of_clusters, random_state=1, affinity='nearest_neighbors'),
    DBSCAN(**best_dbscan_params)
]

data = []
algo_names = ['K-means', 'MiniBatchKMeans', 'AgglomerativeClustering', 'SpectralClustering', 'DBSCAN']
for algo, name in zip(algorithms, algo_names):
    algo.fit(X)
    num_labels = len(set(algo.labels_))
    if num_labels > 1:  # Ensure at least 2 clusters for silhouette score
        try:
            silhouette_score_value = metrics.silhouette_score(X, algo.labels_)
        except ValueError as e:
            print(f"Error calculating silhouette score for {algo.__class__.__name__}: {e}")
            silhouette_score_value = None
        data.append({
            'Algorithm': name,
            'ARI': metrics.adjusted_rand_score(y, algo.labels_),
            'AMI': metrics.adjusted_mutual_info_score(y, algo.labels_, average_method='arithmetic'),
            'Homogeneity': metrics.homogeneity_score(y, algo.labels_),
            'Completeness': metrics.completeness_score(y, algo.labels_),
            'V-measure': metrics.v_measure_score(y, algo.labels_),
            'Silhouette': silhouette_score_value
        })
    else:
        print(f"Skipping silhouette score calculation for {algo.__class__.__name__}: Only 1 cluster found")
        data.append({
            'Algorithm': name,
            'ARI': metrics.adjusted_rand_score(y, algo.labels_),
            'AMI': metrics.adjusted_mutual_info_score(y, algo.labels_, average_method='arithmetic'),
            'Homogeneity': metrics.homogeneity_score(y, algo.labels_),
            'Completeness': metrics.completeness_score(y, algo.labels_),
            'V-measure': metrics.v_measure_score(y, algo.labels_),
            'Silhouette': None
        })

results = pd.DataFrame(data, columns=['Algorithm', 'ARI', 'AMI', 'Homogeneity', 'Completeness', 'V-measure', 'Silhouette'])
results.set_index('Algorithm', inplace=True)

print(results)

In [ ]:
from sklearn.mixture import GaussianMixture
from sklearn.mixture import BayesianGaussianMixture

number_of_clusters=2

algorithms = []
algorithms.append(GaussianMixture(n_components= number_of_clusters, random_state=42, n_init=10))
algorithms.append(BayesianGaussianMixture(n_components=number_of_clusters, random_state=42))

data = []
for algo in algorithms:

    algo.fit(X)
    predicted_label =algo.predict(X)
    data.append(({
        'ARI': metrics.adjusted_rand_score(y, predicted_label),
        'AMI': metrics.adjusted_mutual_info_score(y, predicted_label,
                                               average_method='arithmetic'),
        'Homogenity': metrics.homogeneity_score(y, predicted_label),
        'Completeness': metrics.completeness_score(y, predicted_label),
        'V-measure': metrics.v_measure_score(y, predicted_label),
        'Silhouette': metrics.silhouette_score(X, predicted_label)}))

results2 = pd.DataFrame(data=data, columns=['ARI', 'AMI', 'Homogenity',
                                           'Completeness', 'V-measure',
                                           'Silhouette'],
                       index=['GaussianMixture','BayesianGaussianMixture' ])

results2